name: Build and Deploy
on:
  push:
    branches:
      - main  # replace with your default branch if not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.11.0

      - name: Install Dependencies
        run: cd interface && npm ci
      
      - name: Run Tests
        run: cd interface && npm test

      - name: Build
        run: cd interface && npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.fix-my-budget-token }}
          publish_dir: ./interface/out
